display:
  inverted: false
  orientation: 270
ticker:
  currency: 'bitcoin,ethereum,link'
  fiatcurrency: usd
  timeframes: '7,30,365,1'
  updatefrequency: 300
  randomquotes:
    - TOO THE MOON!
    - TAKE PROFITS -> DIVERSIFY
    - TIME IN THE MARKET >>>
